config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from infoMFSS import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sass_page', views.sass_page_handler),
    # path(r'^chaining/', include('smart_selects.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('infoMFSS.urls', namespace='mfss')),
    path('users/', include('users.urls', namespace='users')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infoMFSS/urls.py
from django.urls import path
from django.views.generic import TemplateView

from infoMFSS.apps import InfomfssConfig
from infoMFSS.views import (BeaconListView, BeaconView, BoxListView,
                            BranchesBoxView, CableFileListView, CableListView,
                            CableMagazineView, CableView, ContactFormView,
                            CreateBeaconView, CreateBranchesBoxView,
                            CreateCableMagazineView, CreateCableView,
                            CreateDateView, CreateEquipmentInstallationView,
                            CreateEquipmentView, CreateExecutionView,
                            CreatePointPhoneView, CreateViolationsView,
                            CreateVisualView, DeleteBeaconView,
                            DeleteBranchesBoxView, DeleteCableMagazineView,
                            DeleteCableView, DeleteEquipmentInstallationView,
                            DeleteEquipmentView, DeleteExecutionView,
                            DeletePointPhoneView, DeleteViolationsView,
                            DeleteVisualView, EquipmentFileListView,
                            EquipmentInstallationView, EquipmentListView,
                            EquipmentView, ExecutionView,
                            MFSSPercentTemplateView, PercentView,
                            PointPhoneView, ProjectCableListView,
                            ProjectEquipmentListView,
                            QuantityEquipmentCableView, UpdateBeaconView,
                            UpdateBranchesBoxView, UpdateCableMagazineView,
                            UpdateCableView, UpdateEquipmentInstallationView,
                            UpdateEquipmentView, UpdateExecutionView,
                            UpdatePointPhoneView, UpdateViolationsView,
                            UpdateVisualView, ViolationsListView,
                            ViolationsView, VisualistView, VisualView)

# from mfss.views import SubsystemTemplateView
# from infoMFSS.views import index

app_name = InfomfssConfig.name

urlpatterns = [
    path("", MFSSPercentTemplateView.as_view(), name="home"),
    path("percents/", PercentView.as_view(), name="percents"),
    path("equipment_list/", EquipmentListView.as_view(), name="equipment"),
    path("cable_list/", CableListView.as_view(), name="cable"),
    path("box_list/", BoxListView.as_view(), name="box"),
    path("equipment_file/", EquipmentFileListView.as_view(), name="equipment_file"),
    path("cable_file/", CableFileListView.as_view(), name="cable_file"),
    path("violations/", ViolationsListView.as_view(), name="violations"),
    path("visual/", VisualView.as_view(), name="visual"),
    path("project_equipment/", ProjectEquipmentListView.as_view(), name="project_equipment"),
    path("project_cable/", ProjectCableListView.as_view(), name="project_cable"),
    path("contact/", ContactFormView.as_view(), name="contact"),
    path(
        "contact/success/", TemplateView.as_view(template_name="infoMFSS/contact_success.html"), name="contact_success"
    ),
    path(
        "quantity/",
        QuantityEquipmentCableView.as_view(template_name="infoMFSS/quantity_equipment_cable.html"),
        name="quantity_equipment_cable",
    ),
    path("beacon_list/", BeaconListView.as_view(), name="beacon"),
    # Создание (только для модератора)
    path("moderator/create/equipment/", CreateEquipmentView.as_view(), name="create_equipment"),
    path("moderator/create/cable/", CreateCableView.as_view(), name="create_cable"),
    path("moderator/create/beacon/", CreateBeaconView.as_view(), name="create_beacon"),
    path("moderator/create/pointphone/", CreatePointPhoneView.as_view(), name="create_pointphone"),
    path("moderator/create/branchesbox/", CreateBranchesBoxView.as_view(), name="create_branchesbox"),
    path("moderator/create/cablemagazine/", CreateCableMagazineView.as_view(), name="create_cablemagazine"),
    path("moderator/create/violations/", CreateViolationsView.as_view(), name="create_violations"),
    path("moderator/create/visual/", CreateVisualView.as_view(), name="create_visual"),
    path(
        "moderator/create/equipment-installation/",
        CreateEquipmentInstallationView.as_view(),
        name="create_equipment_installation",
    ),
    path("moderator/create/execution/", CreateExecutionView.as_view(), name="create_execution"),
    path("moderator/create/date/", CreateDateView.as_view(), name="create_date"),
    # Просмотр и выбор для редактирования и удаления (только для модератора)
    path("moderator/list/equipment/", EquipmentView.as_view(), name="equipment_list"),
    path("moderator/list/cable/", CableView.as_view(), name="cable_list"),
    path("moderator/list/beacon/", BeaconView.as_view(), name="beacon_list"),
    path("moderator/list/point_phone/", PointPhoneView.as_view(), name="point_phone_list"),
    path("moderator/list/branches_box/", BranchesBoxView.as_view(), name="branches_box_list"),
    path("moderator/list/cable_magazine/", CableMagazineView.as_view(), name="cable_magazine_list"),
    path("moderator/list/violations/", ViolationsView.as_view(), name="violations_list"),
    path("moderator/list/visual/", VisualistView.as_view(), name="visual_list"),
    path(
        "moderator/list/equipment_installation/",
        EquipmentInstallationView.as_view(),
        name="equipment_installation_list",
    ),
    path("moderator/list/execution/", ExecutionView.as_view(), name="execution_list"),
    # Редактирование (только для модератора)
    path("moderator/update/equipment/<int:pk>", UpdateEquipmentView.as_view(), name="equipment_update"),
    path("moderator/update/cable/<int:pk>", UpdateCableView.as_view(), name="cable_update"),
    path("moderator/update/beacon/<int:pk>", UpdateBeaconView.as_view(), name="beacon_update"),
    path("moderator/update/point_phone/<int:pk>", UpdatePointPhoneView.as_view(), name="point_phone_update"),
    path("moderator/update/branchesbox/<int:pk>", UpdateBranchesBoxView.as_view(), name="branchesbox_update"),
    path("moderator/update/cablemagazine/<int:pk>", UpdateCableMagazineView.as_view(), name="cablemagazine_update"),
    path("moderator/update/violations/<int:pk>", UpdateViolationsView.as_view(), name="violations_update"),
    path("moderator/update/visual/<int:pk>", UpdateVisualView.as_view(), name="visual_update"),
    path(
        "moderator/update/equipment_installation/<int:pk>",
        UpdateEquipmentInstallationView.as_view(),
        name="equipment_installation_update",
    ),
    path("moderator/update/execution/<int:pk>", UpdateExecutionView.as_view(), name="execution_update"),
    # Удаление (только для модератора)
    path("moderator/delete/equipment/<int:pk>", DeleteEquipmentView.as_view(), name="equipment_delete"),
    path("moderator/delete/cable/<int:pk>", DeleteCableView.as_view(), name="cable_delete"),
    path("moderator/delete/beacon/<int:pk>", DeleteBeaconView.as_view(), name="beacon_delete"),
    path("moderator/delete/point_phone/<int:pk>", DeletePointPhoneView.as_view(), name="point_phone_delete"),
    path("moderator/delete/branchesbox/<int:pk>", DeleteBranchesBoxView.as_view(), name="branchesbox_delete"),
    path("moderator/delete/cablemagazine/<int:pk>", DeleteCableMagazineView.as_view(), name="cablemagazine_delete"),
    path("moderator/delete/violations/<int:pk>", DeleteViolationsView.as_view(), name="violations_delete"),
    path("moderator/delete/visual/<int:pk>", DeleteVisualView.as_view(), name="visual_delete"),
    path(
        "moderator/delete/equipment_installation/<int:pk>",
        DeleteEquipmentInstallationView.as_view(),
        name="equipment_installation_delete",
    ),
    path("moderator/delete/execution/<int:pk>", DeleteExecutionView.as_view(), name="execution_delete"),
]

users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, PasswordEditDoneView,
                         PasswordEditView, RegisterDoneView, RegisterView,
                         SMSVerificationView, UserUpdateView, user_activate)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("verify-sms/", SMSVerificationView.as_view(), name="verify_sms"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/register/done/", RegisterDoneView.as_view(), name="register_done"),
    path("accounts/activate/<str:sign>", user_activate, name="activate"),
    path("accounts/profile/", UserUpdateView.as_view(), name="profile"),
    # path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path(
        "accounts/profile/edit/",
        PasswordEditView.as_view(),
        name="profile_edit",
    ),
    path(
        "accounts/profile/edit/done/",
        PasswordEditDoneView.as_view(),
        name="profile_edit_done",
    ),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

infoMFSS/templates/mfss/contact_success.html
{% extends 'users/base.html' %}
{% block navbar %}
    {% include 'mfss/includes/navbar_home.html' %}
{% endblock %}
{% block content %}
    <div class="container margin-auth-block">
        <div class="row text-start mx-auto mt-4 mb-sm-5">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                <div class="card-body mb-3 mt-3 text-center">
                    <h9>Спасибо за ваше сообщение!</h9>
                    <br>
                    <h10>В ближайшее время мы обработаем и исправим ошибки!</h10>
                    <div class="container mt-4 text-center">
                        <p><a class="color-text-violet underline-none text-center"
                              href=" {% url 'mfss:home' %}">Вернуться на сайт</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

infoMFSS/templates/mfss/equipment_file_list.html
{% extends 'mfss/base.html' %}
{% load crispy_forms_tags %}
{#{% load sass_tags %}#}
{% block navbar %}
    {% include 'mfss/includes/navbar_home.html' %}
{% endblock %}

{% block content %}

    {% include 'mfss/includes/add_table_css.html' %}

    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col text-start">
            <a href="{% url 'mfss:equipment_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
                Оборудование
            </a>
        </div>
        <div class="col text-end">
            <a href="{% url 'mfss:cable_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                Кабель
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
            </a>
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5 table-responsive">
                <table
                        id="Table"
                        class="table table-hover table-bordered table-sm"
                        data-toggle="table"
                        data-pagination="true"
                        data-search="true"
                        data-show-pagination-switch="true"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-show-columns="true"
                        data-show-fullscreen="true"
                        data-buttons-prefix="btn-sm btn"
                        data-buttons-attribute-title="data-hint"
                        data-search-align="left"
                        data-toolbar="#toolbar"
                        data-loading-template="loadingTemplate"
                        data-show-print="true"
                >
                    <thead >
                    <tr class="box-table-th">
                        <th class="align-middle" data-field="equipment" data-sortable="true">Оборудование</th>
                        <th class="align-middle" data-field="subsystem" data-sortable="true">Подсистема</th>
                        <th class="align-middle" data-field="description">Описание</th>
                        <th class="text-center text-danger data" data-field="file_pdf" data-width="110">Руководство</th>
                        <th class="text-center text-danger" data-field="file_passport" data-width="110">Паспорт</th>
                        <th class="text-center text-danger" data-field="file_certificate"
                            data-width="110">Сертификат</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for equipment_file in equipment_file_list %}
                        {% if equipment_file.title != 'Все оборудование' %}
                            <tr class="box-table-td">
                            <td class="align-middle">{{ equipment_file.title }}</td>
                            <td class="align-middle">{{ equipment_file.subsystem }}</td>
                            <td class="align-middle">{{ equipment_file.description }}</td>

                            {% if equipment_file.file_pdf %}
                                <td class="text-center align-middle"><a class="btn!important btn-link!important" Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_pdf.url }}">Просмотр</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if equipment_file.file_passport %}
                                <td class="text-center align-middle"><a class="btn!important btn-link!important" Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_passport.url }}">Просмотр</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if equipment_filefile_certificate %}
                                <td class="text-center align-middle"><a class="btn!important btn-link!important" Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_certificate.url }}">Просмотр</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'mfss/includes/add_table_javascript.html' %}

{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

infoMFSS/templates/mfss/project_cable_list.html
{% extends 'mfss/base.html' %}
{% load crispy_forms_tags %}
{#{% load sass_tags %}#}

{% block navbar %}
    {% include 'mfss/includes/navbar_home.html' %}
{% endblock %}

{% block content %}

    {% include 'mfss/includes/add_table_css.html' %}

    <div class="container text-center mt-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="row text-center">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col text-start">
            <a href="{% url 'mfss:project_equipment' %}" class="color-text-violet-contents underline-none"
               type="button">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
                Оборудование
            </a>
        </div>
        <div class="col text-end">
            <a href="{% url 'mfss:project_cable' %}" class="color-text-violet-contents underline-none"
               type="button">

                Кабель
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
            </a>
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
    <div class="container margin-auth-block">
        <form method="post" action="{% url 'mfss:project_cable' %}">
            <div class="row text-center mx-auto mt-4 mb-sm-5">
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4 card mb-3 box-shadow card-imad-auth border-none">
                    <div class="card-body mt-2 text-center">
                        <h4 class="my-0 font-weight-normal">
                            Фильтр
                        </h4>
                    </div>
                    <div class="card-body text-start">
                        {#                        {% load crispy_forms_tags %}#}
                        {% csrf_token %}
                        {% crispy form %}
                        <button type="submit" class="btn elem-button btn-md">
                            Применить
                        </button>
                    </div>
                </div>
                <div class="col-sm-4">
                </div>
            </div>
        </form>
        {#        </form>#}
        <div class="container text-center">
            {% if mine is not None %}
                {% if project_cable_list %}
                    <h9>По критериям: {{ mine }}
                        &#8594;
                        {{ subsystem }}
                        &#9989;
                    </h9>
                {% else %}
                    <h9a>По критериям: {{ mine }}
                        &#8594;
                        {{ subsystem }}
                        &#10060;
                    </h9a><br><br>
                    <h9a>Данные отсутствуют</h9a><br><br><br>
                {% endif %}
            {% endif %}
        </div>
        <div class="container text-center mb-5">
            <div class="mt-sm-3 mb-sm-5">
                <div class="container mb-5 table-responsive">
                    {% if project_cable_list %}
                        <table
                                id="Table"
                                class="table table-hover table-bordered table-sm"
                                data-toggle="table"
                                data-pagination="true"
                                data-search="true"
                                data-show-pagination-switch="true"
                                data-show-refresh="true"
                                data-show-toggle="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-buttons-prefix="btn-sm btn"
                                data-buttons-attribute-title="data-hint"
                                data-search-align="left"
                                data-toolbar="#toolbar"
                                data-loading-template="loadingTemplate"
                                data-show-print="true"
                        >
                        <thead>
                        <tr class="box-table-th">
                            <th class="align-middle" data-field="number_mine" data-sortable="true" data-width="110">Шахта</th>
                            <th class="align-middle" data-field="subsystem" data-sortable="true">Подсистема</th>
                            <th class="align-middle" data-field="track_from_box" data-sortable="true">Начало трассы</th>
                            <th class="align-middle" data-field="track_to_box" data-sortable="true">Конец трассы</th>
                            <th class="align-middle" data-field="inclined_blocks" data-sortable="true">Уклонный блок</th>
                            <th class="align-middle" data-field="distance" data-sortable="true">Протяженность</th>
                            <th class="align-middle" data-field="cable" data-sortable="true">Марка кабеля</th>
                            <th class="align-middle" data-field="name" data-sortable="true">Обозначение в проекте</th>
                            <th class="align-middle" data-field="cable_bool" data-sortable="true">Проложен</th>
                        </tr>
                        </thead>
                    {% endif %}
                    <tbody>
                    {% for object in project_cable_list %}
                        {% if object %}
                            <tr class="box-table-td">
                                <td class="align-middle">{{ object.number_mine.title }}</td>
                                <td class="align-middle">{{ object.subsystem.title }}</td>
                                <td class="align-middle">{{ object.track_from_box.title }}
                                    ({{ object.track_from_box.tunnel.title }})
                                </td>
                                {% if object.track_to_box.title %}
                                    <td class="align-middle">{{ object.track_to_box.title }}
                                        ({{ object.track_to_box.tunnel.title }})
                                    </td>
                                {% else %}
                                    <td class="align-middle">{{ object.track_to_phone.title }}
                                        ({{ object.track_to_phone.tunnel.title }})
                                        ({{ object.track_to_phone.subscriber_number }})
                                    </td>
                                {% endif %}
                                <td class="align-middle">{{ object.inclined_blocks.title }}</td>
                                <td class="align-middle">{{ object.distance }}</td>
                                <td class="align-middle">{{ object.cable.title }}</td>
                                <td class="align-middle">{{ object.name }}</td>
                                {% if object.cable_bool.execution_bool == True %}
                                    <td class="align-middle text-center">&#9989;</td>
                                {% else %}
                                    <td class="align-middle text-center">&#128500;</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% include 'mfss/includes/add_table_javascript.html' %}

{% endblock %}
{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

infoMFSS/templates/mfss/quantity_equipment_cable.html
{% extends 'mfss/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'mfss/includes/navbar_home.html' %}
{% endblock %}

{% block content %}
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="container margin-auth-block">
        <form method="post" action="{% url 'mfss:quantity_equipment_cable' %}">
            <div class="row text-center mx-auto mt-4 mb-sm-1">
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4 card mb-3 box-shadow card-imad-auth border-none">
                    <div class="card-body mt-2 text-center">
                        <h4 class="my-0 font-weight-normal">
                            Фильтр
                        </h4>
                    </div>
                    <div class="card-body text-start">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <button type="submit" class="btn elem-button btn-md">
                            Применить
                        </button>
                    </div>
                </div>
                <div class="col-sm-4">
                </div>
            </div>
        </form>
    </div>

    <div class="container ">
        <div class="row mx-auto">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-4 mx-5">
                {% if mine is not None %}
                    <h9>Нефтешахта: {{ mine }}</h9><br>
                    {% if equipment %}
                        <h9>Оборудование: {{ equipment }}</h9><br>
                    {% elif cable %}
                        <h9>Кабель: {{ cable }}</h9><br>
                    {% endif %}
                    {% if equipment %}
                        <h9>Количество: {{ quantity }} шт.</h9>
                    {% elif cable %}
                        <h9>Количество: {{ total_length }} м.</h9>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-sm-4">
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}