config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from infoMFSS import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sass_page', views.sass_page_handler),
    # path(r'^chaining/', include('smart_selects.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('infoMFSS.urls', namespace='mfss')),
    path('users/', include('users.urls', namespace='users')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, PasswordEditDoneView,
                         PasswordEditView, RegisterDoneView, RegisterView,
                         SMSVerificationView, UserUpdateView, user_activate)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("verify-sms/", SMSVerificationView.as_view(), name="verify_sms"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/register/done/", RegisterDoneView.as_view(), name="register_done"),
    path("accounts/activate/<str:sign>", user_activate, name="activate"),
    path("accounts/profile/", UserUpdateView.as_view(), name="profile"),
    # path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path(
        "accounts/profile/edit/",
        PasswordEditView.as_view(),
        name="profile_edit",
    ),
    path(
        "accounts/profile/edit/done/",
        PasswordEditDoneView.as_view(),
        name="profile_edit_done",
    ),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

users/models.py
import logging

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

NULLABLE = {"null": True, "blank": True}

logger = logging.getLogger(__name__)


class User(AbstractUser):
    username = None

    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
    )
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
    )
    middle_name = models.CharField(
        max_length=50,
        verbose_name="Отчество",
    )
    email = models.EmailField(unique=True, verbose_name="E-mail", **NULLABLE)
    phone = models.CharField(max_length=12, verbose_name="Номер телефона", **NULLABLE)
    telegram_id = models.CharField(max_length=50, unique=True, verbose_name="telegram_id", **NULLABLE)
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Прошел активацию?")
    location_of_work = models.CharField(
        max_length=50,
        verbose_name="Место работы",
    )
    post = models.CharField(
        max_length=50,
        verbose_name="Должность",
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        is_new = self._state.adding  # Проверяем, что объект новый
        super().save(*args, **kwargs)
        if is_new:
            logger.info(
                f"Создан новый пользователь: {self.last_name} (ID: {self.id})",
                extra={"classname": self.__class__.__name__},
            )


class AllowedPerson(models.Model):
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
    )  # Фамилия
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
    )  # Имя
    middle_name = models.CharField(
        max_length=50,
        verbose_name="Отчество",
    )  # Отчество (необязательно)
    is_active = models.BooleanField(default=True)  # Можно отключать пользователей

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

    def save(self, *args, **kwargs):
        is_new = self._state.adding  # Проверяем, что объект новый
        super().save(*args, **kwargs)
        if is_new:
            logger.info(
                f"Добавлен разрешенный пользователь: {self.last_name} (ID: {self.id})",
                extra={"classname": self.__class__.__name__},
            )

    class Meta:
        verbose_name = "Разрешенный пользователь"
        verbose_name_plural = "Разрешенные пользователи"
        ordering = ["last_name"]


class SMSDevice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)

    def is_valid(self):
        return (timezone.now() - self.created_at).seconds < 300  # 5 минут

users/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError

# from catalog.forms import StyleFormMixin
from users.models import User
from users.signals import post_register

from .models import AllowedPerson


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_staff":
                field.widget.attrs["class"] = "form-control"


class UserProfileForm(StyleFormMixin, UserChangeForm):
    """Добавление формы профиля пользователя"""

    class Meta:
        model = User
        fields = (
            "last_name",
            "first_name",
            "middle_name",
            "email",
            "phone",
            "location_of_work",
            "post",
            "password",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()


class RegisterForm(StyleFormMixin, UserCreationForm):
    """Добавление формы регистрации пользователя с верификацией"""

    phone = forms.CharField(
        max_length=12,
        widget=forms.TextInput(
            attrs={
                "placeholder": "+7XXXXXXXXXX",  # Подсказка в поле
                "value": "+7",  # Автоматическое значение
            }
        ),
        label="Номер телефона",
        required=True,
    )

    class Meta:
        model = User
        fields = (
            "last_name",
            "first_name",
            "middle_name",
            "email",
            "phone",
            "location_of_work",
            "post",
        )

    def clean(self):
        cleaned_data = super().clean()
        phone = cleaned_data.get("phone")
        last_name = cleaned_data.get("last_name")
        first_name = cleaned_data.get("first_name")
        middle_name = cleaned_data.get("middle_name")

        if phone:
            if not phone.startswith("+7"):
                self.add_error("phone", "Номер телефона должен начинаться с '+7'.")

        digits = phone[2:]
        if not re.match(r"^\d{10}$", digits):  # Проверяем, что оставшиеся 10 символов — цифры
            self.add_error("phone", "Введите 10 цифр после '+7'.")

            # Проверяем, есть ли ФИО в списке разрешённых
        if not AllowedPerson.objects.filter(
            last_name=last_name, first_name=first_name, middle_name=middle_name, is_active=True
        ).exists():
            raise ValidationError(
                "Ваши ФИО не входят в список разрешённых для регистрации. Обратитесь пожалуйста к администратору "
                "ресурса."
            )

            # Проверяем, существует ли пользователь с такими же ФИО
        if User.objects.filter(
            last_name=last_name,
            first_name=first_name,
            middle_name=middle_name,
        ).exists():
            raise ValidationError("Пользователь с такими ФИО уже зарегистрирован.")

        if User.objects.filter(
            phone=phone,
        ).exists():
            # raise ValidationError("Пользователь с таким номером телефона уже зарегистрирован.")
            self.add_error("phone", "Пользователь с таким номером телефона уже зарегистрирован.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        post_register.send(RegisterForm, instance=user)
        return user


class SMSVerificationForm(forms.Form):
    code = forms.CharField(
        label=False,
        max_length=4,
        min_length=4,
        widget=forms.TextInput(
            attrs={
                "autocomplete": "off",
                "style": "width: 200px; height: 50px;",
                "class": "mx-auto d-block",
                "placeholder": "Введите 4-х значный код",
            }
        ),
    )

users/views.py
import logging
from random import randint

from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.views import (PasswordChangeDoneView,
                                       PasswordChangeView)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, UpdateView
from django.views.generic.base import TemplateView

from infoMFSS.services_logger import LoggingMixin, logger_form_valid
from users.forms import RegisterForm, SMSVerificationForm, UserProfileForm
from users.models import User

from .models import SMSDevice
from .sms_utils import send_sms_via_smsc
from .utilities import signer

logger = logging.getLogger(__name__)


class LoginView(LoggingMixin, BaseLoginView):
    template_name = "users/login.html"
    extra_context = {
        "title": "Весь функционал доступен только зарегистрированным пользователям",
    }

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        user = authenticate(username=username, password=form.cleaned_data.get("password"))
        if user:
            # Генерация и отправка кода
            code = str(randint(1000, 9999))
            response = send_sms_via_smsc(user.phone, code)

            if response.get("error"):
                logger.error(f'Ошибка отправки СМС на номер телефона: {user.phone}: {response["error"]}')
                form.add_error(None, "Ошибка отправки SMS. Попробуйте позже.")
                return self.form_invalid(form)

            # Сохранение кода в БД
            SMSDevice.objects.create(user=user, code=code)
            self.request.session["sms_user_id"] = user.id  # Сохраняем ID для верификации
            self.request.session["sms_user_phone"] = user.phone  # Сохраняем номер телефона для верификации

            logger.info(f"Код отправлен пользователю {username}")
            return redirect("users:verify_sms")  # Перенаправляем на страницу ввода кода

        logger.warning(f"Неудачная попытка входа для {username}")
        return super().form_invalid(form)


class SMSVerificationView(FormView):
    template_name = "users/verify_sms.html"
    form_class = SMSVerificationForm  # Форма с полем code
    success_url = reverse_lazy("infoMFSS:home")  # URL после успешной верификации

    def form_valid(self, form):
        user_id = self.request.session.get("sms_user_id")
        code = form.cleaned_data["code"]

        if user_id:
            try:
                device = SMSDevice.objects.get(user_id=user_id, code=code, is_verified=False)
                device.is_verified = True
                device.save()

                user = device.user
                login(self.request, user)  # Финализируем вход
                logger.info(f"Пользователь {user.username} успешно верифицирован")
                return super().form_valid(form)

            except SMSDevice.DoesNotExist:
                logger.warning(f"Неверный код для пользователя ID {user_id}")
                form.add_error(None, "Неверный код или срок действия истёк")

        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_phone"] = self.request.session.get("sms_user_phone")
        return context


class LogoutView(BaseLogoutView):

    def dispatch(self, request, *args, **kwargs):
        logger.info(
            f"Запрос: {request.method} {request.path}/выход из системы", extra={"classname": self.__class__.__name__}
        )
        return super().dispatch(request, *args, **kwargs)


class RegisterView(LoggingMixin, CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy("users:register_done")
    extra_context = {
        "title": "Регистрация",
    }
    template_name = "users/register.html"
    success_message = "Вы успешно зарегистрировались"

    def form_valid(self, form):
        logger_form_valid(self)
        return super().form_valid(form)


class RegisterDoneView(TemplateView):
    template_name = "users/register_done.html"
    # extra_context = {
    #         'title': "Регистрация",
    # }


def user_activate(request, sign):
    try:
        email = signer.unsign(sign)
    except BadSignature:
        return render(request, "users/activation_failed.html")

    user = get_object_or_404(User, email=email)

    if user.is_activated:
        logger.info(f"Пользователь: {user.email} уже был активирован ранее", extra={"classname": __name__})
        template = "users/activation_done_earlier.html"
    else:
        logger.info(f"Активация прошла удачно. Пользователь: {user.email}", extra={"classname": __name__})
        template = "users/activation_done.html"
        user.is_active = True
        user.is_activated = True
        user.save()

    return render(request, template)


class UserUpdateView(LoggingMixin, LoginRequiredMixin, UpdateView):
    models = User
    success_url = reverse_lazy("mfss:home")
    form_class = UserProfileForm
    extra_context = {
        "title": "Профиль",
    }

    def get_object(self, queryset=None):  # Избавляемся от входящего параметра pk
        return self.request.user

    def form_valid(self, form):
        logger_form_valid(self)
        return super().form_valid(form)


class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = "users/password_edit.html"
    success_url = reverse_lazy("users:profile_edit_done")
    success_message = "Пароль успешно изменен"

    def dispatch(self, request, *args, **kwargs):
        logger.info(
            f"Запрос: {request.method} {request.path}{request.user.last_name}/запрос изменения пароля",
            extra={"classname": self.__class__.__name__},
        )
        return super().dispatch(request, *args, **kwargs)


class PasswordEditDoneView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeDoneView):
    template_name = "users/password_update_complete.html"

    def dispatch(self, request, *args, **kwargs):
        logger.info(
            f"Запрос: {request.method} {request.path}{request.user.last_name}/пароль изменен",
            extra={"classname": self.__class__.__name__},
        )
        return super().dispatch(request, *args, **kwargs)

users/templates/users/activation_done.html
{% extends 'users/base.html' %}
{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <div class="row text-center mx-auto mt-4 mb-sm-5">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                <div class="card-body mb-3 mt-3 text-center">
                    <h9>Пользователь с таким E-mail успешно активирован</h9>
                    <div class="container mt-5 text-center">
                        <p><a class="color-text-violet underline-none text-center"
                              href=" {% url 'users:login' %}">Войти в систему</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/activation_done_earlier.html
{% extends 'users/base.html' %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <div class="row text-start mx-auto mt-4 mb-sm-5">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                <div class="card-body mb-3 mt-3 text-center">
                    <h9>Пользователь с таким E-mail был активирован ранее</h9>
                    <div class="container mt-5 text-center">
                        <p><a class="color-text-violet underline-none text-center"
                              href=" {% url 'users:login' %}">Войти на сайт</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/activation_failed.html
{% extends 'users/base.html' %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <div class="row text-center mx-auto mt-4 mb-sm-5">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                <div class="card-body mb-3 mt-3 text-center">
                    <h9>Активация пользователя с таким именем прошла неудачно.</h9>
                    <div class="container mt-5 text-center">
                    <p><a class="color-text-violet underline-none text-center"
                          href=" {% url 'users:register' %}">Зарегистрироваться повторно</a></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/base.html
{% load static %}
{% load sass_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Александр Струльков">
    <title>Информационный ресурс</title>
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% sass_src 'css/main.scss' %}" rel="stylesheet" type="text/css"/>

</head>
<body>
    {#    <!-- Navbar __>#}
    {% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
    {% endblock %}

    {#    <!_-- Main content __>#}
    <main>
    {% block content %}
        {#    Сюда вставляются все остальные файлы HTML#}
    {% endblock %}
    </main>

    {#    <!_-- Footer __>#}
    {% block footer %}
    {% include 'users/includes/auth_footer.html' %}
    {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
{#<script src={% static "js/bootstrap.bundle.min.js" %}></script>#}
</body>

</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="container margin-auth-block">
        <form method="post">
            <div class="row text-start mx-auto mt-4 mb-sm-5">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                    <div class="card-body">
                        <h5 class="card-title mb-4">Вход</h5>
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <div class="text-end mb-4">
                        <a class="ms-5 text-end color-text-violet underline-none" href="{% url 'users:password_reset' %}">Забыли
                            пароль?</a>
                        </div>
                        <div class="text-center mb-4">
                        <button type="submit" class="btn elem-button btn-md mx-2 pull-right">
{#                        <button class="btn btn-primary pull-right">#}
                            Войти
                        </button>
                        </div>
                        <div class="text-center mb-3">
                        <a class="color-text-violet underline-none"
                           href="{% url "users:register" %}">Зарегистрироваться</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/password_edit.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <form method="post">
            <div class="row text-start mx-auto mt-4 mb-sm-5">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                    <div class="card-body mb-3 mt-3">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <button type="submit" class="btn elem-button btn-md mx-2">
                            Сменить пароль
                        </button>
                    </div>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <form method="post">
            <div class="row text-start mx-auto mt-4 mb-sm-5">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                    <div class="card-body mb-3 mt-3">
{#                        <form method="post">#}
                            {% load crispy_forms_tags %}
                            {% csrf_token %}
                            {% crispy form %}
                            <button type="submit" class="btn elem-button btn-md mx-2">
                                Сохранить
                            </button>

                            {#                        <a class="ms-5" href="{% url 'users:profile_edit' %}">Сбросить по E-mail</a>#}
                    </div>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "users/base.html" %}
{% load i18n %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <div class="row mx-auto mt-4 mb-sm-5">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6 mb-5 card-imad-auth">
                <div class="container mt-4">
                    <p>
                        {% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}
                    </p>
                </div>
                    <div class="container mb-4">
                    <p>
                        {% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}
                    </p>
                </div>
            </div>
            <div class="col-sm-3">
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{#{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}#}
{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <form method="post">
            <div class="row text-start mx-auto mt-4 mb-sm-5">
                <div class="col-sm">
                </div>
                <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                    <div class="card-body mb-3 mt-3">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <button type="submit" class="btn elem-button btn-md mx-2">
                            Сбросить по E-mail
                        </button>
{#                        <a class="ms-5" href="{% url 'users:profile_edit' %}">Сбросить по E-mail</a>#}
                    </div>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container text-center mt-5 mb-3">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-3">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="container">
        <form method="post">
            <div class="row text-start mx-auto mt-1 mb-sm-3">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-6 card mb-5 box-shadow card-imad-auth border-none">
                    <div class="card-body mb-3 mt-3">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <button type="submit" class="btn elem-button btn-md mx-2">
                            Выполнить
                        </button>
                    </div>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'users/includes/auth_navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container margin-auth-block">
        <form method="post">
            <div class="row mx-auto mt-sm-4 mb-sm-4">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-6 card mb-4 box-shadow card-imad-auth border-none">
                    <div class="card-body mb-3 mt-3">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy form %}
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn elem-button btn-md mx-2">
                                    Изменить данные
                                </button>
                            </div>
                            <div class="col text-end mt-3">
                                <a class="color-text-violet underline-none text-end"
                                   href="{% url 'users:profile_edit' %}">Сменить пароль</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}