config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from infoMFSS import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sass_page', views.sass_page_handler),
    # path(r'^chaining/', include('smart_selects.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('infoMFSS.urls', namespace='mfss')),
    path('users/', include('users.urls', namespace='users')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infoMFSS/urls.py
from django.urls import path
from django.views.generic import TemplateView

from infoMFSS.apps import InfomfssConfig
from infoMFSS.views import (BeaconListView, BeaconView, BoxListView,
                            BranchesBoxView, CableFileListView, CableListView,
                            CableMagazineView, CableView, ContactFormView,
                            CreateBeaconView, CreateBranchesBoxView,
                            CreateCableMagazineView, CreateCableView,
                            CreateDateView, CreateEquipmentInstallationView,
                            CreateEquipmentView, CreateExecutionView,
                            CreatePointPhoneView, CreateViolationsView,
                            CreateVisualView, DeleteBeaconView,
                            DeleteBranchesBoxView, DeleteCableMagazineView,
                            DeleteCableView, DeleteEquipmentInstallationView,
                            DeleteEquipmentView, DeleteExecutionView,
                            DeletePointPhoneView, DeleteViolationsView,
                            DeleteVisualView, EquipmentFileListView,
                            EquipmentInstallationView, EquipmentListView,
                            EquipmentView, ExecutionView,
                            MFSSPercentTemplateView, PercentView,
                            PointPhoneView, ProjectCableListView,
                            ProjectEquipmentListView,
                            QuantityEquipmentCableView, UpdateBeaconView,
                            UpdateBranchesBoxView, UpdateCableMagazineView,
                            UpdateCableView, UpdateEquipmentInstallationView,
                            UpdateEquipmentView, UpdateExecutionView,
                            UpdatePointPhoneView, UpdateViolationsView,
                            UpdateVisualView, ViolationsListView,
                            ViolationsView, VisualistView, VisualView)

# from mfss.views import SubsystemTemplateView
# from infoMFSS.views import index

app_name = InfomfssConfig.name

urlpatterns = [
    path("", MFSSPercentTemplateView.as_view(), name="home"),
    path("percents/", PercentView.as_view(), name="percents"),
    path("equipment_list/", EquipmentListView.as_view(), name="equipment"),
    path("cable_list/", CableListView.as_view(), name="cable"),
    path("box_list/", BoxListView.as_view(), name="box"),
    path("equipment_file/", EquipmentFileListView.as_view(), name="equipment_file"),
    path("cable_file/", CableFileListView.as_view(), name="cable_file"),
    path("violations/", ViolationsListView.as_view(), name="violations"),
    path("visual/", VisualView.as_view(), name="visual"),
    path("project_equipment/", ProjectEquipmentListView.as_view(), name="project_equipment"),
    path("project_cable/", ProjectCableListView.as_view(), name="project_cable"),
    path("contact/", ContactFormView.as_view(), name="contact"),
    path(
        "contact/success/", TemplateView.as_view(template_name="infoMFSS/contact_success.html"), name="contact_success"
    ),
    path(
        "quantity/",
        QuantityEquipmentCableView.as_view(template_name="infoMFSS/quantity_equipment_cable.html"),
        name="quantity_equipment_cable",
    ),
    path("beacon_list/", BeaconListView.as_view(), name="beacon"),
    # Создание (только для модератора)
    path("moderator/create/equipment/", CreateEquipmentView.as_view(), name="create_equipment"),
    path("moderator/create/cable/", CreateCableView.as_view(), name="create_cable"),
    path("moderator/create/beacon/", CreateBeaconView.as_view(), name="create_beacon"),
    path("moderator/create/pointphone/", CreatePointPhoneView.as_view(), name="create_pointphone"),
    path("moderator/create/branchesbox/", CreateBranchesBoxView.as_view(), name="create_branchesbox"),
    path("moderator/create/cablemagazine/", CreateCableMagazineView.as_view(), name="create_cablemagazine"),
    path("moderator/create/violations/", CreateViolationsView.as_view(), name="create_violations"),
    path("moderator/create/visual/", CreateVisualView.as_view(), name="create_visual"),
    path(
        "moderator/create/equipment-installation/",
        CreateEquipmentInstallationView.as_view(),
        name="create_equipment_installation",
    ),
    path("moderator/create/execution/", CreateExecutionView.as_view(), name="create_execution"),
    path("moderator/create/date/", CreateDateView.as_view(), name="create_date"),
    # Просмотр и выбор для редактирования и удаления (только для модератора)
    path("moderator/list/equipment/", EquipmentView.as_view(), name="equipment_list"),
    path("moderator/list/cable/", CableView.as_view(), name="cable_list"),
    path("moderator/list/beacon/", BeaconView.as_view(), name="beacon_list"),
    path("moderator/list/point_phone/", PointPhoneView.as_view(), name="point_phone_list"),
    path("moderator/list/branches_box/", BranchesBoxView.as_view(), name="branches_box_list"),
    path("moderator/list/cable_magazine/", CableMagazineView.as_view(), name="cable_magazine_list"),
    path("moderator/list/violations/", ViolationsView.as_view(), name="violations_list"),
    path("moderator/list/visual/", VisualistView.as_view(), name="visual_list"),
    path(
        "moderator/list/equipment_installation/",
        EquipmentInstallationView.as_view(),
        name="equipment_installation_list",
    ),
    path("moderator/list/execution/", ExecutionView.as_view(), name="execution_list"),
    # Редактирование (только для модератора)
    path("moderator/update/equipment/<int:pk>", UpdateEquipmentView.as_view(), name="equipment_update"),
    path("moderator/update/cable/<int:pk>", UpdateCableView.as_view(), name="cable_update"),
    path("moderator/update/beacon/<int:pk>", UpdateBeaconView.as_view(), name="beacon_update"),
    path("moderator/update/point_phone/<int:pk>", UpdatePointPhoneView.as_view(), name="point_phone_update"),
    path("moderator/update/branchesbox/<int:pk>", UpdateBranchesBoxView.as_view(), name="branchesbox_update"),
    path("moderator/update/cablemagazine/<int:pk>", UpdateCableMagazineView.as_view(), name="cablemagazine_update"),
    path("moderator/update/violations/<int:pk>", UpdateViolationsView.as_view(), name="violations_update"),
    path("moderator/update/visual/<int:pk>", UpdateVisualView.as_view(), name="visual_update"),
    path(
        "moderator/update/equipment_installation/<int:pk>",
        UpdateEquipmentInstallationView.as_view(),
        name="equipment_installation_update",
    ),
    path("moderator/update/execution/<int:pk>", UpdateExecutionView.as_view(), name="execution_update"),
    # Удаление (только для модератора)
    path("moderator/delete/equipment/<int:pk>", DeleteEquipmentView.as_view(), name="equipment_delete"),
    path("moderator/delete/cable/<int:pk>", DeleteCableView.as_view(), name="cable_delete"),
    path("moderator/delete/beacon/<int:pk>", DeleteBeaconView.as_view(), name="beacon_delete"),
    path("moderator/delete/point_phone/<int:pk>", DeletePointPhoneView.as_view(), name="point_phone_delete"),
    path("moderator/delete/branchesbox/<int:pk>", DeleteBranchesBoxView.as_view(), name="branchesbox_delete"),
    path("moderator/delete/cablemagazine/<int:pk>", DeleteCableMagazineView.as_view(), name="cablemagazine_delete"),
    path("moderator/delete/violations/<int:pk>", DeleteViolationsView.as_view(), name="violations_delete"),
    path("moderator/delete/visual/<int:pk>", DeleteVisualView.as_view(), name="visual_delete"),
    path(
        "moderator/delete/equipment_installation/<int:pk>",
        DeleteEquipmentInstallationView.as_view(),
        name="equipment_installation_delete",
    ),
    path("moderator/delete/execution/<int:pk>", DeleteExecutionView.as_view(), name="execution_delete"),
]

users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, PasswordEditDoneView,
                         PasswordEditView, RegisterDoneView, RegisterView,
                         SMSVerificationView, UserUpdateView, user_activate)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("verify-sms/", SMSVerificationView.as_view(), name="verify_sms"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/register/done/", RegisterDoneView.as_view(), name="register_done"),
    path("accounts/activate/<str:sign>", user_activate, name="activate"),
    path("accounts/profile/", UserUpdateView.as_view(), name="profile"),
    # path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path(
        "accounts/profile/edit/",
        PasswordEditView.as_view(),
        name="profile_edit",
    ),
    path(
        "accounts/profile/edit/done/",
        PasswordEditDoneView.as_view(),
        name="profile_edit_done",
    ),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

infoMFSS/templates/infoMFSS/cable_file_list.html
{% extends 'infoMFSS/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'infoMFSS/includes/navbar_home.html' %}
{% endblock %}

{% block content %}

    {% include 'infoMFSS/includes/add_table_css.html' %}

    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col text-start">
            <a href="{% url 'mfss:equipment_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
                Оборудование
            </a>
        </div>
        <div class="col text-end">
            <a href="{% url 'mfss:cable_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                Кабель
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
            </a>
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5 table-responsive">
                <table
                        id="Table"
                        class="table table-hover table-bordered table-sm"
                        data-toggle="table"
                        data-pagination="true"
                        data-search="true"
                        data-show-pagination-switch="true"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-show-columns="true"
                        data-show-fullscreen="true"
                        data-buttons-prefix="btn-sm btn"
                        data-buttons-attribute-title="data-hint"
                        data-search-align="left"
                        data-toolbar="#toolbar"
                        data-loading-template="loadingTemplate"
                        data-show-print="true"
                >
                    <thead>
                    <tr class="box-table-td">
                        <th class="align-middle" data-field="cable" data-sortable="true">Кабель</th>
                        <th class="align-middle" data-field="device_type" data-sortable="true">Тип</th>
                        <th class="align-middle">Описание</th>
                        <th class="text-center text-danger align-middle" data-field="file_pdf"
                            data-width="110">Руководство</th>
                        <th class="text-center text-danger align-middle" data-field="file_passport"
                            data-width="110">Паспорт</th>
                        <th class="text-center text-danger align-middle" data-field="file_certificate"
                            data-width="110">Сертификат</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cable_file in cable_file_list %}
                        {% if cable_file.title != 'Все кабели' %}
                            <tr class="box-table-td">
                            <td class="align-middle">{{ cable_file.title }}</td>
                            <td class="align-middle">{{ cable_file.device_type }}</td>
                            <td class="align-middle">{{ cable_file.description }}</td>

                            {% if cable_file.file_pdf %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none" Style="color:#6d37ff;"
                                                           href="{{ cable_file.file_pdf.url }}">📤</a></td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if cable_file.file_passport %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none" Style="color:#6d37ff;"
                                                           href="{{ cable_file.file_passport.url }}">📤</a></td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if cable_file.file_certificate %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none" Style="color:#6d37ff;"
                                                           href="{{ cable_file.file_certificate.url }}">📤</a></td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}
                        {% endif %}

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'infoMFSS/includes/add_table_javascript.html' %}

{% endblock %}
{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

infoMFSS/templates/infoMFSS/equipment_file_list.html
{% extends 'infoMFSS/base.html' %}
{% load crispy_forms_tags %}
{#{% load sass_tags %}#}
{% block navbar %}
    {% include 'infoMFSS/includes/navbar_home.html' %}
{% endblock %}

{% block content %}

    {% include 'infoMFSS/includes/add_table_css.html' %}

    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col text-start">
            <a href="{% url 'mfss:equipment_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
                Оборудование
            </a>
        </div>
        <div class="col text-end">
            <a href="{% url 'mfss:cable_file' %}" class="color-text-violet-contents underline-none"
               type="button">
                Кабель
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 1C1.44772 1 1 1.44772 1 2V14C1 14.5523 1.44772 15 2 15H14C14.5523 15 15 14.5523 15 14V2C15 1.44772 14.5523 1 14 1H9.5C8.94771 1 8.5 1.44772 8.5 2V9.29289L11.1464 6.64645C11.3417 6.45118 11.6583 6.45118 11.8536 6.64645C12.0488 6.84171 12.0488 7.15829 11.8536 7.35355L8.35355 10.8536C8.15829 11.0488 7.84171 11.0488 7.64645 10.8536L4.14645 7.35355C3.95118 7.15829 3.95118 6.84171 4.14645 6.64645C4.34171 6.45118 4.65829 6.45118 4.85355 6.64645L7.5 9.29289V2C7.5 0.895431 8.39543 0 9.5 0H14C15.1046 0 16 0.895431 16 2V14C16 15.1046 15.1046 16 14 16H2C0.89543 16 0 15.1046 0 14V2C0 0.895431 0.895431 0 2 0H4.5C4.77614 0 5 0.223858 5 0.5C5 0.776142 4.77614 1 4.5 1H2Z"/>
                </svg>
            </a>
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5 table-responsive">
                <table
                        id="Table"
                        class="table table-hover table-bordered table-sm"
                        data-toggle="table"
                        data-pagination="true"
                        data-search="true"
                        data-show-pagination-switch="true"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-show-columns="true"
                        data-show-fullscreen="true"
                        data-buttons-prefix="btn-sm btn"
                        data-buttons-attribute-title="data-hint"
                        data-search-align="left"
                        data-toolbar="#toolbar"
                        data-loading-template="loadingTemplate"
                        data-show-print="true"
                >
                    <thead>
                    <tr class="box-table-th">
                        <th class="align-middle" data-field="equipment" data-sortable="true">Оборудование</th>
                        <th class="align-middle" data-field="device_type" data-sortable="true">Тип</th>
                        <th class="align-middle" data-field="subsystem" data-sortable="true">Подсистема</th>
                        <th class="align-middle" data-field="description">Описание</th>
                        <th class="text-center text-danger data" data-field="file_pdf" data-width="110">Руководство</th>
                        <th class="text-center text-danger" data-field="file_passport" data-width="110">Паспорт</th>
                        <th class="text-center text-danger" data-field="file_certificate"
                            data-width="110">Сертификат
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for equipment_file in equipment_file_list %}
                        {% if equipment_file.title != 'Все оборудование' %}
                            <tr class="box-table-td">
                            <td class="align-middle">{{ equipment_file.title }}</td>
                            <td class="align-middle">{{ equipment_file.device_type }}</td>
                            <td data-field="subsystem" class="text-start">
                                {% if equipment_file.subsystem %}
                                    <span
                                            data-bs-toggle="tooltip"
                                            data-bs-custom-class="tooltip-card"
                                            title="{{ equipment_file.subsystem.description|default:'Нет описания'|escape }}">
                                                {{ equipment_file.subsystem.title }}
                                        </span>
                                {% else %}
                                    <span class="text-muted">Без подсистемы</span>
                                {% endif %}
                            </td>
                            {% include 'infoMFSS/includes/include_tooltip_subsystem.html' %}
                            <td class="align-middle">{{ equipment_file.description }}</td>

                            {% if equipment_file.file_pdf %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none"
                                                                        Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_pdf.url }}">📤</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if equipment_file.file_passport %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none"
                                                                        Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_passport.url }}">📤</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}

                            {% if equipment_filefile_certificate %}
                                <td class="text-center align-middle"><a class="btn!important text-decoration-none"
                                                                        Style="color:#6d37ff;"
                                                                        href="{{ equipment_file.file_certificate.url }}">📤</a>
                                </td>
                            {% else %}
                                <td class="text-center align-middle"><a>-</a></td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'infoMFSS/includes/add_table_javascript.html' %}

{% endblock %}

{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}

infoMFSS/templates/infoMFSS/execution.html
{% extends 'infoMFSS/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
    {% include 'infoMFSS/includes/navbar_home.html' %}
{% endblock %}

{% block content %}

    {% include 'infoMFSS/includes/add_table_css.html' %}

    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5">
                <h8>
                    {{ title }}
                </h8>
                <br>
            </div>
        </div>
    </div>
    <div class="container text-center mt-5 mb-5">
        <div class="mt-sm-5 mb-sm-5">
            <div class="container mt-5 mb-5 table-responsive">
                <table
                        id="Table"
                        class="table table-hover table-bordered table-sm"
                        data-toggle="table"
                        data-pagination="true"
                        data-search="true"
                        data-show-pagination-switch="true"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-show-columns="true"
                        data-show-fullscreen="true"
                        data-buttons-prefix="btn-sm btn"
                        data-buttons-attribute-title="data-hint"
                        data-search-align="left"
                        data-toolbar="#toolbar"
                        data-loading-template="loadingTemplate"
                        data-show-print="true"
                >
                    <thead>
                    <tr class="box-table-th">
                        <th class="align-middle" data-sortable="true">Список оборудования</th>
                         <th class="align-middle" data-sortable="true">Список трасс кабелей</th>
{#                        <th class="align-middle text-center" data-width="110">Дата начала</th>#}
                        <th class="align-middle text-center" data-width="110">Дата начала</th>
                        <th class="align-middle text-center" data-width="110">Дата окончания</th>
                        <th class="align-middle text-center" data-width="110">Выполнено</th>
                        <th class="text-center text-danger align-middle" data-width="110">Редактировать</th>
                        <th class="text-center text-danger align-middle" data-width="110">Удалить</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for execution in execution_list %}
                        <tr class="box-table-td">
                        {% if execution.equipment_install is not None %}
                            <td class="align-middle text-start">{{ execution.equipment_install.title.title }}-
                                ({{ execution.equipment_install.name }}) - {{ execution.equipment_install.number_mine }}</td>
                        {% else %}
                            <td class="align-middle">&#128500;</td>
                        {% endif %}

                         {% if execution.cable_magazine is not None %}
                        <td class="align-middle text-start">{{ execution.cable_magazine.cable.device_type }} (
                            {{ execution.cable_magazine.name }}) - {{ execution.cable_magazine.number_mine }}</td>
                        {% else %}
                        <td class="align-middle">&#128500;</td>
                        {% endif %}

                        <td class="align-middle">{{ execution.date_start|date:'d.m.Y' }}</td>
                        <td class="align-middle">{{ execution.date_end|date:'d.m.Y' }}</td>
                        {% if execution.execution_bool == True %}
                          <td class="align-middle text-center">&#9989;</td>
                        {% else %}
                        <td class="align-middle text-center">&#10060;</td>
{#                            <td class="align-middle text-center">&#128500;</td>#}
                        {% endif %}
                        <td class="text-center align-middle"><a class="btn!important text-decoration-none"
                                                                href="{% url 'mfss:execution_update' execution.pk %}">🛠️</a>
                        </td>
                        <td class="text-center align-middle"><a class="btn!important text-decoration-none"
                                                                href="{% url 'mfss:execution_delete' execution.pk %}">🗑️</a>
                        </td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% include 'infoMFSS/includes/add_table_javascript.html' %}

{% endblock %}
{% block footer %}
    {% include 'users/includes/auth_footer.html' %}
{% endblock %}